### ISSUE TITLE
Cannot find [LImageOverlay] after install package

### ISSUE THREAD

**Issue by louistruong10** [vue-leaflet/vue-leaflet#102]
Hi all,

After I run `yarn add  @vue-leaflet/vue-leaflet` I cannot find [LImageOverlay] in component and function,

Please help me

![image](https://user-images.githubusercontent.com/62685897/109542220-5fefe480-7af7-11eb-8c89-f49ac2faccb7.png)

**Comment by mathiash98** [comment]
I think you need to verify that you actually have version 0.6.0 installed (check package.json).
- It could be that the npm package registry had some cache laying around if you tried to install latest right after latest version was pushed.
Mine is working, using it in production now:
![image](https://user-images.githubusercontent.com/5204006/109966460-95135700-7cf0-11eb-9bad-2a7c21953257.png)

**Comment by mikeu** [comment]
With a fresh installation of v0.6.0, I see the same result as @mathiash98—thank you for that confirmation!

So at the moment I don't believe this is an issue with the library, but please report back if you are still running into trouble after verifying the installed version, @louistruong10.
