### ISSUE TITLE
l-control-layers

### ISSUE THREAD

**Issue by parkb83** [vue-leaflet/vue-leaflet#107]
Just an observation, when using l-control-layers, is it normal for all of the base layers to be 'active' when the map is first loaded? Looking at the network tab, when panning/zooming all base layers load. It isn't until a layer is selected, that just that layer is loaded when panning/zooming.

Thanks
parkb83

**Comment by mikeu** [comment]
@parkb83 I think this is basically the same problem as addressed in [this comment on Vue2Leaflet](https://github.com/vue-leaflet/Vue2Leaflet/issues/568#issuecomment-676510146). Does it work if you set `visible: false` on the base layers that you don't want to be initially visible?

**Comment by parkb83** [comment]
@mikeu thanks for the reply, adding :visible="false" works as expected .Thanks
