### ISSUE TITLE
Is there a way to use the .getBounds() function?

### ISSUE THREAD

**Issue by JEK58** [vue-leaflet/vue-leaflet#112]
I need to get the bounds of a polyline but cannot manage to access the` .getbounds()` function.

This is what I have:

```import "leaflet/dist/leaflet.css";
import { LMap,  LTileLayer,  LPolyline } from "@vue-leaflet/vue-leaflet";

export default {
  components: {    LMap,    LTileLayer,   LPolyline,  },

methods: {
    doSomethingOnReady() {
      this.map = this.$refs.map.leafletObject;
      this.track = this.$refs.track.leafletObject;
      this.map.fitBounds(this.track.getBounds());
    },
  },
```

Any idea what I'm missing?

**Comment by mikeu** [comment]
Hi @JEK58 , thanks for the question, I believe that should be able to work so definitely an issue somewhere...

You don't say when your `doSomethingOnReady` is called so it's hard to say for sure, but my first guess would be that you are using it in the `@ready` event of your map, instead of the one for the polyline. Is that the case? And, if so, does moving it to `<l-polyline @ready="doSomethingOnReady" ...>` resolve the issue?

**Comment by JEK58** [comment]
Thank you. You were right, I was using ```doSomethingOnReady``` in the map, but unfortunately moving it to the polyline does not solve the problem.

I tried calling ```doSomethingOnReady```from a button manually to make sure it's not about the timing but no luck.

This is what I get as an error:

```
runtime-core.esm-bundler.js:217 Uncaught TypeError: this.track.getBounds is not a function
    at Proxy.doSomethingOnReady (MapV3.vue:95)
    at Object.onClick._cache.<computed>._cache.<computed> (MapV3.vue:30)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:333)
```

**Comment by mikeu** [comment]
Sorry to hear it's still not working, @JEK58 . Are you able to share a minimal working example that reproduces the issue? What you're describing is working for me, so without seeing a complete example of the code that isn't working for you it's tricky to guess where the problem might lie.

Here's a pared down version of what I've tried, which successfully logs the resulting bounds to the console:
```vue
<template>
  <l-map>
    <l-polyline
      ref="track"
      @ready="doSomethingOnReady"
      :lat-lngs="[[0, 0], [1, 1]]"
    />
  </l-map>
</template>
<script>
import { LMap, LPolyline } from "@vue-leaflet/vue-leaflet";

export default {
  components: {
    LMap,
    LPolyline,
  },
  methods: {
    doSomethingOnReady() {
      this.track = this.$refs.track.leafletObject;
      console.log("Bounds:", this.track.getBounds());
    },
  },
};
</script>
```

**Comment by JEK58** [comment]
I somehow managed to forget the `leafletObject` at the end of `this.track = this.$refs.track.leafletObject;`…
Now it's working. Thank you very much!
