### ISSUE TITLE
LMarker doesn't work

### ISSUE THREAD

**Issue by Kameecoding** [vue-leaflet/vue-leaflet#130]
Version: ^0.6.0
Leaflet: 1.7.1

MY error:
[localhost-1623349224480.log](https://github.com/vue-leaflet/vue-leaflet/files/6633608/localhost-1623349224480.log)

Error when running the demo project:
```

Uncaught (in promise) TypeError: options.icon is undefined
    _initIcon leaflet-src.esm.js:7542
    onAdd leaflet-src.esm.js:7449
    _layerAdd leaflet-src.esm.js:6561
    whenReady leaflet-src.esm.js:4422
    addLayer leaflet-src.esm.js:6623
    addLayer vue-leaflet.esm.js:416
    wrapper vue-leaflet.esm.js:148
    setup vue-leaflet.esm.js:782
    callWithErrorHandling runtime-core.esm-bundler.js:154
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:163
    __weh runtime-core.esm-bundler.js:2908
    flushPostFlushCbs runtime-core.esm-bundler.js:357
    flushJobs runtime-core.esm-bundler.js:393
    promise callback*queueFlush runtime-core.esm-bundler.js:286
    queueJob runtime-core.esm-bundler.js:280
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    scheduler reactivity.esm-bundler.js:854
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    set reactivity.esm-bundler.js:298
    setup vue-leaflet.esm.js:529
    callWithErrorHandling runtime-core.esm-bundler.js:154
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:163
    __weh runtime-core.esm-bundler.js:2908
    flushPostFlushCbs runtime-core.esm-bundler.js:357
    render runtime-core.esm-bundler.js:5776
    mount runtime-core.esm-bundler.js:4070
    mount runtime-dom.esm-bundler.js:1288
    <anonymous> main.js:4
    js app.js:1078
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1091
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonymous> app.js:994
    <anonymous> app.js:997
leaflet-src.esm.js:7542
```

Steps to reproduce:

1. Add any LMarker
2. Use any of LPopup, LIcon, LTooltip

**Comment by MicroLink26** [comment]
Same problem after update, it was working before.
Does anyone have any idea on how to fix it?

**Comment by mikeu** [comment]
Hi @Kameecoding and @MicroLink26 , thank you for reporting this issue! Can either of you provide a repo that demonstrates this problem, or further details on what you're doing before seeing it, your environment, what your code looks like, etc.?

I have run both the demo project in this repo, and the older [vue3-demo-project](https://github.com/vue-leaflet/vue3-demo-project), using v0.6.0 with Leaflet v1.7.1, and have not encountered this or any other error, while using markers, popups, icons, tooltips, or any other components.

**Comment by Kameecoding** [comment]
Checkout the the vue3-demo-project, ran `npm install`  then `npm run serve` opened in Firefox  88.0.1 (64-bit), OS: Arch Linux

message: 
```
Uncaught (in promise) TypeError: options.icon is undefined
    _initIcon leaflet-src.esm.js:7542
    onAdd leaflet-src.esm.js:7449
    _layerAdd leaflet-src.esm.js:6561
    whenReady leaflet-src.esm.js:4422
    addLayer leaflet-src.esm.js:6623
    addLayer vue-leaflet.esm.js:416
    wrapper vue-leaflet.esm.js:148
    setup vue-leaflet.esm.js:782
leaflet-src.esm.js:7542
```

The attached message I have as a log in the Issue is from Chromium Version 90.0.4430.212 (Official Build) Arch Linux (64-bit)

**Comment by mikeu** [comment]
Well now that is strange... I am seeing the error now when I follow _exactly_ those steps, but if I instead run `yarn install` then `yarn serve`, then the demo project works as expected.

I'll try to dig further into why this might be happening this week, but presumably npm is installing a different version of something somewhere (or possibly invoking a different version of `vue-cli-service`) than yarn is.

Are you able to confirm that if you use yarn instead, then the demo project doesn't throw the error?

**Comment by Kameecoding** [comment]
Can confirm, works with Yarn

**Comment by Kameecoding** [comment]
I checked after yarn install and it has vue-leaflet 0.3.0 I tried locking it to 0.3.0 on my project but that didn't help, both yarn and npm installs leaflet 1.7.1

**Comment by Kameecoding** [comment]
[package.tar.gz](https://github.com/vue-leaflet/vue-leaflet/files/6644958/package.tar.gz)

```
"dependencies": {
    "@vue-leaflet/vue-leaflet": "^0.6.0",
    "core-js": "^3.6.5",
    "leaflet": "^1.7.1",
    "vue": "^3.0.9"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.0-alpha5",
    "@vue/cli-plugin-eslint": "~5.0.0-alpha5",
    "@vue/cli-service": "~5.0.0-alpha5",
    "@vue/compiler-sfc": "^3.0.0-0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.5.0",
    "eslint-plugin-vue": "^7.6.0"
  },
```
Reproduced on yarn:

1. Bumped @vue-leaflet to 0.6.0
2. Vue-cli plugins to 5.0-alpha5 and esling to 7.5.0
3. then bumped vue to 3.0.9 which finally reproduced the issue
