### ISSUE TITLE
LPolyline not updating with new array values

### ISSUE THREAD

**Issue by CRBroughton** [vue-leaflet/vue-leaflet#133]
I'm trying to get the LPolyline component to create a path. I can easily create a path like so, and it shows up on the map:

```javascript
 <l-polyline :lat-lngs="[[49.05047019529438,1.7427062988281252],[48.62383195130112,1.9212341308593752]]" color="green"/> 
```

However when I try the following, it doesn't show any path on the map when arrays are added using the below method (assume the below has the correct npm packages and imports etc and that the method is being triggered by a button):

```javascript

<l-polyline :lat-lngs="path" color="green"/>

export default {
data() {
 path: [],
}
,
methods: {
   runpathFinder() {
      const tempLoc = [this.center.lat, this.center.lng];
      this.path.push(...[tempLoc]);
      console.log(this.path);
    },
};

```

I've tried using the Vue extension to check to ensure that the this.path array is being updated correctly, which is appears to be doing so, so I'm at a bit of a loss as to why the second example doesn't want to work.

**Comment by mikeu** [comment]
Hi @CRBroughton , thank you for reporting this issue! At the moment there is no watcher on the `lat-lngs` prop of the `l-polyline` to update the underlying [Leaflet Polyline](https://leafletjs.com/reference-1.7.1.html#polyline) when the array changes. You can however work with that underlying Leaflet object directly, with something such as:
```js
<l-polyline ref="path" :lat-lngs="[]" color="green"/>

export default {
  methods: {
    runpathFinder() {
      const tempLoc = [this.center.lat, this.center.lng];
      this.$refs.path.leafletObject.addLatLng(tempLoc);
    }
  },
};
```

Will something like that work for your use case?

**Comment by CRBroughton** [comment]
> Hi @CRBroughton , thank you for reporting this issue! At the moment there is no watcher on the `lat-lngs` prop of the `l-polyline` to update the underlying [Leaflet Polyline](https://leafletjs.com/reference-1.7.1.html#polyline) when the array changes. You can however work with that underlying Leaflet object directly, with something such as:
> 
> ```js
> <l-polyline ref="path" :lat-lngs="[]" color="green"/>
> 
> export default {
>   methods: {
>     runpathFinder() {
>       const tempLoc = [this.center.lat, this.center.lng];
>       this.$refs.path.leafletObject.addLatLng(tempLoc);
>     }
>   },
> };
> ```
> 
> Will something like that work for your use case?

Thanks for the reply. How would I do the same but for the composition api? I've been looking for documentation on the "this.$refs.path" equivalent but I'm having a little trouble finding it.

**Comment by CRBroughton** [comment]
@mikeu Sorry to bother you again with this, but is there anyway to reset the Leaflet object to clear out any latlngs it has been given?

**Comment by mikeu** [comment]
@CRBroughton not a problem :)

When you reference the `leafletObject` of a vue-leaflet component, you are directly accessing the corresponding object created by the Leaflet library, in this case [L.polyline](https://leafletjs.com/reference-1.7.1.html#polyline). That means that you have access to every method and property provided by Leaflet for that object.

In particular in this case, that means that you can use `path.value.leafletObject.setLatLngs([])` to replace the existing set of positions with an empty array.

**Comment by CRBroughton** [comment]
> path.value.leafletObject.setLatLngs([])

Thanks for the reply. Just tested it and it works fine. Thanks again for the amazing help :)

**Comment by lindaifu** [comment]
LPolyline add a random key

`
let randomKey = 'key-' + Math.random()
...
<LPolyline 
    :latLngs="pointData"
    :key="randomKey"
/>`
