### ISSUE TITLE
Gray Tile No Map

### ISSUE THREAD

**Issue by omaromp2** [vue-leaflet/vue-leaflet#135]
The map opens with no error. However, it just appears as a gray tile, and it doesn't display an error. 
![image](https://user-images.githubusercontent.com/3978597/122997858-693cdf80-d37a-11eb-817b-127ec8cb2e5d.png)

**Comment by mikeu** [comment]
Hi @omaromp2 , to me that looks like a map with no layers added to it, although it is very hard to tell much more than that without seeing any of your code. Are you able to share the relevant portion of your code that creates the map, or provide a link to a repo that reproduces the issue?

Once we have a better idea of what you've already tried, I'm sure we'll be able to get your map to display as expected!

**Comment by omaromp2** [comment]
Hi @mikeu, thanks for the quick reply. 
I'm basically following the example in the docs. 

https://gist.github.com/omaromp2/bc81edfa3feb1dbc5d7b9d0d1801bef8

**Comment by omaromp2** [comment]
Got it to work! @mikeu you were right about the layers! 
Thank you, very much! 
![image](https://user-images.githubusercontent.com/3978597/123332713-df724b00-d50e-11eb-89b1-8bcdb6d86c6f.png)
