### ISSUE TITLE
Inertia effect on dragging

### ISSUE THREAD

**Issue by xfifi** [vue-leaflet/vue-leaflet#136]
Hello here,

I have set up a basic test map here: https://www.ridersmap.fr/test-map
I use Laravel with InertiaJs + VueJs.

I would like to have the effect of inertia when moving on the map with the mouse on desktop or with the fingers on mobile.
I thought it was a default effect in LeafLet but it doesn't work.
I also tried to put the props: inertia = "true" in <l-map: inertia = "true" ...> then also via <l-map: options = "{intertia =" true "}". ..> but that did not change anything.

Thank you

Here is the code of my MapTest.vue page:

```
<template>
        <div class="container max-w-6xl px-5 py-24 mx-auto text-gray-600">
            <div class="" style="height: 75vh;">
                <l-map :center="[46.35878473119541, -0.38761961748339097]" v-model:zoom="zoom" :min-zoom="minZoom" :max-zoom="maxZoom" :zoomAnimation="true" :options="mapOptions">
                    <l-tile-layer :url="url" :attribution="attribution" ></l-tile-layer>
                </l-map>
            </div>
        </div>
</template>

<script>
    import AppLayout from '@/Layouts/RidersMapLayout'
    import { LMap, LTileLayer } from '@vue-leaflet/vue-leaflet'

export default {
    components: {   
        AppLayout,
        LMap,
        LTileLayer,

    },
    data() {
    return {
      zoom: 6,
      minZoom: 1,
      maxZoom: 20,
      url: 'https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png',
      attribution: '<div class="flex"><p>Affichage de cartes par <a href="https://leafletjs.com" title="Leaflet, bibliothèque JavaScript libre de cartographie en ligne">Leaflet</a><p></div><div class="flex "><p>Fond de carte &copy; <a href="https://www.openstreetmap.fr/mentions-legales/" target="_blank">OpenStreetMap France</a> sous <a href="https://creativecommons.org/licenses/by-sa/2.0/deed.fr" target="_blank">licence libre CC BY-SA</a></p></div><div class="flex"><p>Données par &copy; les contributeurs d’<a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> sous <a href="https://opendatacommons.org/licenses/odbl/1.0/" target="_blank">licence libre ODbL</a></p></div>',
      mapOptions: {
          zoomSnap: true,
      },
    }
  },
}
</script>
```

**Comment by mikeu** [comment]
Hi @xfifi , thank you for reporting this issue. The problem looks to me to be that default Leaflet options are in some cases being overridden with `default` when you don't set them.

As a workaround until we get this resolved, you should be able to get the inertia effect you desire by setting all of the related properties explicitly,
```vue
<l-map :inertia="true" :inertiaDeceleration="3000" :inertiaMaxSpeed="Infinity" :easeLinearity="0.2" ...>
```

**Comment by xfifi** [comment]
Hi @mikeu, thanks for answering.
Your proposed workaround has resolved the problem of inertia effect.

Thanks a lot.

**Comment by mikeu** [comment]
Resolved by the update to defaults on all components as of [v0.8.0](https://github.com/vue-leaflet/vue-leaflet/releases/tag/v0.8.0)
