### ISSUE TITLE
vue3 this.$slots.default is not a function

### ISSUE THREAD

**Issue by igpfpyu** [vue-leaflet/vue-leaflet#138]
vue3 this.$slots.default is not a function

**Comment by mikeu** [comment]
@igpfpyu thank you for reporting this issue.

Could you please provide a sample of the code that is leading to the issue, and the Vue template you are using it with?

**Comment by baptistejamin** [comment]
Hello!

We had the exact same problem. It was due to the @vue/compat package loading this library using the Vue 2 rendering function.

We made a patch right here: https://github.com/vue-leaflet/vue-leaflet/pull/147

**Comment by Javid-Izadfar** [comment]
I've got a same error and it looks like come from here:
https://github.com/vue-leaflet/vue-leaflet/blob/852a180777870bd8982c78d2d74d5282f187d9a9/src/components/LMap.vue#L411

The thing is, it only happens when you don't put anything inside the `LMap` (like `<l-map style="height:50vh">`)

**Comment by chatondearu** [comment]
Hi guys ! thanks for your awesome work with vue 3 ! any solution or update about this issue ?@baptistejamin why your Pr was not merged ?

**Comment by nevermin9** [comment]
I found, that if you pass nothing into slots (default/named), it doesn't exist in the `$slots`
this should work `$slots.default && $slots.default()`

**Comment by nicksellen** [comment]
I just ran into this too @nevermin9 and created a PR https://github.com/vue-leaflet/vue-leaflet/pull/218 :)

**Comment by 2233070031** [comment]
I wrote this ‘ const items = this.$slots.default() ’ in the jsx syntax in render().
this.$slots.default is not a function

**Comment by d-koppenhagen** [comment]
Hey, are there any news about this issues? Is there a applicable workaround until the PR from @nicksellen gets merged?

**Comment by WouterSioen** [comment]
I'm running against the same problem, can the fix be merged and released?

**Comment by jaclynt** [comment]
Same problem. Looks like this fix is still pending approvals...
