### ISSUE TITLE
Boundary Canvas

### ISSUE THREAD

**Issue by fickmann** [vue-leaflet/vue-leaflet#140]
Hi, how to make boundary canvas with vue-leaflet?

**Comment by mikeu** [comment]
Hi @fickmann, I'm sorry, I'm not familiar with what a boundary canvas is. It's not something that seems to appear in the Leaflet documentation either. Could you elaborate at all on what you are trying to accomplish?

**Comment by fickmann** [comment]
> 
> 
> Hi @fickmann, I'm sorry, I'm not familiar with what a boundary canvas is. It's not something that seems to appear in the Leaflet documentation either. Could you elaborate at all on what you are trying to accomplish?

Yes, I'm sorry. I just didn't know that this feature does not apply to the standard leaflet. It turned out to be a special separate plugin :/
