### ISSUE TITLE
leafletRef.value.getPopup is not a function

### ISSUE THREAD

**Issue by wirk** [vue-leaflet/vue-leaflet#141]
I have just migrated to the new version from Vue2, and after the map initializes (geoJson renders fine from a user perspective) however, I'm getting the following error in the console 5 times:

> layer.js:89 Uncaught (in promise) TypeError: leafletRef.value.getPopup is not a function
>     at Object.unbindPopup (layer.js:89)
>     at layer.js:110
>     at callWithErrorHandling (runtime-core.esm-bundler.js:155)
>     at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164)
>     at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2910)
>     at flushPostFlushCbs (runtime-core.esm-bundler.js:358)
>     at flushJobs (runtime-core.esm-bundler.js:394)

I am using a pretty complex slotted wrapper component that receives multiple individual map features as child components that register their geoJson or markers with the main component, which then renders them in one place. I have tried removing any Leaflet plugins and isolating the problem, but I haven't been able to recreate the error in a minimal example yet. Please let me know if anyone has encountered the same issue before.

**Comment by wirk** [comment]
I was able to isolate the issue. In the mounted hook, I hide all map features till the next tick:

```vue
<l-geo-json v-if="visible" ref="geoJson" :geojson="geoJson" />
```

``` js
mounted() {
  this.visible = false
  this.$nextTick(() => (this.visible = true))
},
```

This is over simplified, but the reason for doing this has to do with clustering logic that combines markers from multiple features, including l-geojson and l-markers depending on the zoom level, so when the zoom level changes, I need to clear the map of all features and re-render.

Just now I was able to get rid of the error by hiding all map features till the `@ready` event fires. Looks like I was trying to interact with the map too early. I now provide a `leafletReady` variable from my main map component that I inject into my child components.

That said, it probably makes sense to check for the existence of the getPopup method in unbindPopup and unbindTooltip:

```js
unbindPopup() {
  const popup = leafletRef.value && leafletRef.value.getPopup ? leafletRef.value.getPopup() : null;
}
```

**Comment by mikeu** [comment]
Hi @wirk, thank you for the issue report and for attempting to narrow down the problem from what sounds like a complicated edge case race condition! Without a simpler reproduction it's hard to guess what exactly might be leading to the unbinding of a popup from a layer that hasn't actually been created yet. Still, I certainly see no harm in adding the null check you suggest, so I will go ahead and do that soon.

Will that resolve this issue to your satisfaction, or do you still think there is something deeper to be investigated here?

**Comment by wirk** [comment]
Hi @mikeu, thanks for the reply. I think the null checks should be enough to prevent the error from occurring.

**Comment by wirk** [comment]
I've created a [sandbox](https://codesandbox.io/s/trusting-newton-zyb61?file=/components/SampleGeoJson.vue) that reproduces the issue. Uncomment the calls in lines 68 and/or 80 and you should get the error in your console. Basically the `v-if` on the l-geojson sometimes causes the component to be destroyed before it's fully initialized.

**Comment by mikeu** [comment]
Thanks @wirk, that's great to be able to see what you were describing in action. I've uncommented first just 68, then both 68 and 80 together, but so far haven't seen the error (though it did take me a bit to realise that for some reason the logs are now appearing in my actual browser console, not the sandbox one).

I'll try again later in the day, but looking at the code and your description of the issue, I did have one thought—have you tried starting with `visible: false` in your data function?

**Comment by wirk** [comment]
@mikeu that was actually my first vue code sandbox and I just realized it doesn't pick up code changes automatically (not sure if you forked and recompiled it) but I just uncommented 80 saved it again so now the map doesn't render anymore for me - let me know if you see the error now.

Thanks for the suggestion regarding the visible prop, I've actually seen it and have been wondering whether that could be a viable alternative. However, in my actual component I don't actually toggle the same elements but rather swap them out for new ones. I'm using the map to display thousands of markers which may or may not be clustered, depending on the amount of markers currently in the map's bounds and the zoom level. At least in the Vue 2 version, I hit performance issues when directly modifying a large amount of markers which is why I ended up with this solution. I'll give `visible: false` a go to hide the markers that are outside of the map bounds and see how that goes :)

**Comment by mikeu** [comment]
@wirk that is very strange, I forked it, saved it, even reloaded the page in a different browser after making those changes, and wasn't seeing any problems... but on first load of your updated sandbox I saw it!

As for my suggestion re `visible`, I didn't mean to switch away from `v-if` to `:visible` or any other change to your obviously fairly complex logic! I just meant to change the initial value of your `this.visible` data element (in `SampleGeoJson.vue`'s `data()` method, in this case) from `true` (which it currently is) to `false`. That way when the component is created, it by default won't create the geojson at all until after you've set `this.visible = true`. Right now, I think it is creating the geojson then immediately trying to remove it and then on the next tick bring it back again, and that's possibly where this apparent race condition is coming from.

Here's my [newly forked sandbox](https://codesandbox.io/s/gracious-khayyam-6nq8i) that was seeing the error, that no longer is with that one small change. Perhaps it would also resolve the issue in your real scenario, and at the very least might just be a good idea to avoid unnecessary component creations.

**Comment by wirk** [comment]
That makes sense, and it definetely avoids a bunch of component creations in my real app as well. Thanks again!

**Comment by edwh** [comment]
@mikeu Could you do an npm release which includes this?

**Comment by markbaird** [comment]
This fix was merged over a year ago but hasn't been included in a release to npm yet. Is this project abandoned?

**Comment by edwh** [comment]
@markbaird I tried reaching out to @mikeu, but I didn't get a response.  I've emailed @DonNicoJs, who's also an active contributor.
