### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by ShadowZone** [vue-leaflet/vue-leaflet#144]
Hi there,
I'm currently learning how to use vue-leaflet in combination with Leaflet plugins.
I already got many to work, but the leaflet-lasso plugin gives me headaches.

I've prepared a little sandbox example for that: 
https://codesandbox.io/s/vue-leaflet-popup-open-by-default-forked-ysy59

Used versions:
module | version
-------- | --------
Leaflet | 1.7.1
@vue-leaflet/vue-leaflet | 0.6.1
vue | 3.1.5
leaflet-lasso | 2.2.4

Reproducing the problem:
1. click on the little lasso icon in the top right corner of the map
2. click and drag the crossfade anywhere on the map

Expected Behaviour:
- Drawing a Polyline while dragging
- On Mouse Up -> select all markers within the drawn area

Actual Behaviour:
- Error message "Cannot read property 'x' of undefined" in the console and nothing happens on the map

I've investigated the problem a little bit further and found out, there is a problem with the Leaflet #contains and #intersects methods or with the values they receive.

In my debugger I have the following scenario:
![image](https://user-images.githubusercontent.com/976282/126130964-7b9587d8-5854-456b-98d2-1d1c51f323c0.png)
If I go one step further I get an empty Bounds object from the toBounds method.
![image](https://user-images.githubusercontent.com/976282/126131211-4e65371d-f854-4ce6-a4f4-69ddb876e4d7.png)
and then it wants to compare a null value and crashes:
![image](https://user-images.githubusercontent.com/976282/126131460-b7f7058e-5869-4a97-8547-7bf317ee32b1.png)

My colleague tried the same on his machine (local server) and got other results (this time from contains method):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/976282/126132825-4a9f14fd-e74a-4b8f-9e83-1395fcdd0f17.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/976282/126132845-e1f72e73-a8be-4746-8640-5a14d340ff0d.png)

From the screenshots it looks like Bounds !== Bounds and Point !== Point and there is also some weird VUE3 Proxy stuff that could cause some problems.

First I thought, maybe there is something broken on Leaflet site, but the author of the plugin has a running (and working) [DEMO](https://zakjan.github.io/leaflet-lasso/) linked on his [git repo](https://github.com/zakjan/leaflet-lasso) readme.

Also, there are also no known problems when using with [VUE2-Leaflet](https://github.com/vue-leaflet/Vue2Leaflet).

I've spent the last 3 days figuring out what could be the solution to this but I have no idea.
Can you please help me?

**Comment by mikeu** [comment]
Hi @ShadowZone, thank you for the detailed error report, and sorry for the trouble that our current dearth of documentation has caused you. I believe the trouble here is one that we've seen before, and luckily have a quick fix for. If you add the option `:use-global-leaflet="true"` to your `<l-map>`, then I think your plugin should start working as expected.

In a few places throughout its code, Leaflet uses `instanceof` to decide whether it can use an object passed to it. When the LMap component imports asynchronously from the distributed Leaflet ESM, and a plugin imports instead synchronously `from "leaflet"`, the code used to define the `Bounds` objects used by the map and the plugin will be identical, yet because they are imported from different places, neither will be an `instanceof` the other, and Leaflet will end up throwing these bizarre sound errors of Bounds !== Bounds etc.

Additional discussions about this problem can be found in #48, #118, and #125, if you're interested. Let me know if you have any other questions, or if that does not in fact solve your problem!

**Comment by wrightkobe** [comment]
Hi,

Just wanted to chime in and confirm that `:use-global-leaflet="true"` fixed it for me, thanks @mikeu !.

I had a very similar issue using the leaflet-gpx plugin where for a very simple gpx file everything worked, but real life gpx files resulted in the "Cannot read property 'x' of undefined" error.

Guess I got lucky with the timing of this issue, so thanks @ShadowZone :grin: !

**Comment by ShadowZone** [comment]
@mikeu Your solution works absolutely perfectly.
And thank you very much for the detailed explanation!

@wrightkobe Thanks for the mentioning. Wished someone else posted this a week ago 😄 So, you're welcome 😁

**Comment by PickRelated** [comment]
From my understanding, as of today there is no such option as `:use-global-leaflet` anymore. Or it does not work. How can we work with it now? Thanks!

**Comment by bloodykheeng** [comment]
Those doing next js 15 just add ancor points ,
i mean these   iconAnchor ,tooltipAnchor:


// Fix marker icon issue in Leaflet with Webpack
delete (L.Icon.Default.prototype as any)._getIconUrl;

const markerIcon2x = "/react-leaflet-images/marker-icon-2x.png";
const markerIcon = "/react-leaflet-images/marker-icon.png";
const markerShadow = "/react-leaflet-images/marker-shadow.png";

L.Icon.Default.mergeOptions({
  iconRetinaUrl: markerIcon2x,
  iconUrl: markerIcon,
  shadowUrl: markerShadow,

  iconAnchor: [12, 41],        // the point of the icon which will correspond to marker's location (tip of pin)
  popupAnchor: [1, -34],       // point from which the popup should open relative to the iconAnchor
  tooltipAnchor: [12, -41],    // center the tooltip above the tip of the marker
  shadowSize: [41, 41],        // size of the shadow
  shadowAnchor: [12, 41]       // anchor point of the shadow (align with marker tip)
});
