### ISSUE TITLE
How to call leaflet object in Vue3 

### ISSUE THREAD

**Issue by beaumontyun** [vue-leaflet/vue-leaflet#146]
In the past, in Vue2 leaflet,  I would use the following to initiate leaflet object:
` 
<v-map @ready="onLoad">
...
methods: {
    onLoad() {
      this.map = this.$refs.map.mapObject;
    },
flyToTarget() {
      console.log("Acquiring position")
      this.map
        .locate({setView: false, watch: false})
        .on('locationfound', (e) => {
            this.map.flyTo([e.latitude, e.longitude],  13);
        })
    },
...
`

But when I tested this on Vue3, it doesn't seem to work. Any idea how to resolve this?

**Comment by mikeu** [comment]
Hi @beaumontyun, the property has been renamed from `mapObject` to `leafletObject` in this version. Hopefully making that switch will get you up and running!

**Comment by beaumontyun** [comment]
> Hi @beaumontyun, the property has been renamed from `mapObject` to `leafletObject` in this version. Hopefully making that switch will get you up and running!

Mind blown...! Thank you. This resolved the issue.
