### ISSUE TITLE
Error when updating attribution prop for tileLayer

### ISSUE THREAD

**Issue by rumski20** [vue-leaflet/vue-leaflet#165]
I am getting an error while trying to update a `tileLayer` dynamically.
Here is the code for the `tileLayer`:
```
      <l-tile-layer
        :url="basemap.url"
        layer-type="base"
        :attribution="basemap.attribution"
        :name="basemap.name"
      ></l-tile-layer>
```
When I change the value of `basemap`, I get an error (`this.$parent is undefined`) in `layer.js` line 53:
https://github.com/vue-leaflet/vue-leaflet/blob/2996e8a11b5f9c3e897cc01cbf2d06079a6fce90/src/functions/layer.js#L52-L54

If I hardcode the attribution (eg. `attribution="some string"`) it works fine

`basemap` is an object. For example:
```
    {
      name: 'Streets',
      url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>contributors',
      image: 'osm.jpg'
    }
```
For some reason, both `url` and `name` work with `v-bind`. It was only `attribution` that threw the error

The basemap object is a computed object that gets altered by a separate component. So the whole object is getting replaced.

**Comment by mikeu** [comment]
Hi @rumski20 , thank you for reporting this issue! I have reproduced it locally, and found what I believe is a solution to this specifically, but it has also raised some inconsistencies in the attributions no longer always being _removed_ correctly. I'm hoping to have an update for you soon.
