### ISSUE TITLE
How to use l-marker lat-lng syncronization in Vue3?

### ISSUE THREAD

**Issue by imShara** [vue-leaflet/vue-leaflet#168]
In Vue2 we made
```
coords = { lat, lng }

<l-marker
  :lat-lng="coords"
  :lat-lng.sync="coords"
  draggable
></l-marker>
```

In Vue3 [we should make](https://v3.vuejs.org/guide/migration/v-model.html#v-model-arguments)
```
test = { lat, lng }

<l-marker
  :lat-lng="coords"
  @update:lat-lng="coords = $event"
  draggable
></l-marker>
```

But this way not working.

**Comment by mikeu** [comment]
Hi @imShara , thank you for reporting this issue. Could you please provide a little more context on what exactly isn't working, and what the rest of your code looks like? I haven't been able to reproduce the problem; here is a demo of what you describe working as I think you are expecting it to, largely using the code you provided:

https://codesandbox.io/s/vl-marker-lat-lng-sync-vnur8

Perhaps you could fork that demo and update it to a form that should also work but doesn't, or provide a link to a repo that demonstrates the error.

**Comment by imShara** [comment]
@mikeu , thanks, it's really works, but not in my enviroment. Maybe because i'm using scriptsetup composition api. I should make demo.

**Comment by imShara** [comment]
Oh, my bad. Actually, Vue3 supports amazing shortland with model arguments.

![v-bind-instead-of-sync](https://user-images.githubusercontent.com/4913196/143725425-28c83235-96a8-4aac-837b-ee7b54e6bf82.png)
 
Code should look that way:

```vue
import { ref } from 'vue'

coordinates = ref({ lat, lng })

<l-marker
  v-model:lat-lng="coordinates"
  draggable
></l-marker>
```

Note that model should be ref
