### ISSUE TITLE
Blinking default marker when using custom icon component

### ISSUE THREAD

**Issue by imShara** [vue-leaflet/vue-leaflet#170]
I'm using computed collection to draw visible markers in map with `v-for` and custom icon. When marker state changes, it's reloads and blinks with default leaflet icon, which replaces by custom icon from child component when it ready. How to fix this? 

![marker](https://user-images.githubusercontent.com/4913196/144045912-eaf8b904-82c6-49ca-a98e-d00693e007f4.gif)

```vue
<sctipt setup>
import { computed } from 'vue'
const visibleMarkers = computed(() => …)
</sctipt>

<template>
  <l-map>
    <l-tile-layer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />

    <l-layer-group layer-type="overlay" name="Markers">
      <l-marker
        v-for="marker in visibleMarkers"
        :key="marker.id"
        :lat-lng="marker.position"
      >
        <l-icon :icon-anchor="[13, 40]">
          #
        </l-icon>
      </l-marker>
    </l-layer-group>
  </l-map>
</template>
```
It could be hotfixed with dummy icon or pre-creating icon in setup script (better if your icons are static).

```vue
<sctipt setup>
import { computed } from 'vue'
import { divIcon } from 'leaflet'
const visibleMarkers = computed(() => …)
const dummyIcon = divIcon({
  className: 'dummy-icon'
})
</sctipt>

<template>
  <l-map>
    <l-tile-layer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />

    <l-layer-group layer-type="overlay" name="Markers">
      <l-marker
        v-for="marker in visibleMarkers"
        :key="marker.id"
        :lat-lng="marker.position"
        :icon="dummyIcon"
      >
        <l-icon :icon-anchor="[13, 40]">
          #
        </l-icon>
      </l-marker>
    </l-layer-group>
  </l-map>
</template>

<style>
.dummy-icon {
  background: transparent;
  border: none;
}
</style>
```

PS. Is I am wrong with `v-for` loop and computed collection?

**Comment by imShara** [comment]
It's very strange. I tried to modify your sample at first and can't reproduce bug
https://codesandbox.io/s/vl-marker-lat-lng-sync-forked-8ki67?file=/src/App.vue

But then, I have made my own sample and catch it!
https://codesandbox.io/s/upbeat-sutherland-9bbmz?file=/src/components/HelloWorld.vue

![marker2](https://user-images.githubusercontent.com/4913196/144136941-dbce94dd-a33f-43d0-a9ff-2f6e1f974e7d.gif)

The major difference is that in your sample `l-marker` without parameters does not have icon, but in my sample it loads default leaflet icon

**Comment by imShara** [comment]
@mikeu can you confirm that?

**Comment by mikeu** [comment]
Hi @imShara sorry for the delay, but the main reason for it is that yes, I can confirm the issue but unfortunately don't have a quick fix for it. I have to really spam the toggle button, clicking rapidly many times, but I do once or twice see the default marker briefly appear as in your sample.

The problem seems to be that when the `<l-marker>` component mounts, it doesn't know that its icon is going to be replaced by the `<l-icon>` component, so it creates its own default. I think the best solution for the moment is the one you suggested of having a dummy icon that doesn't display anything, and overriding the default with that.

**Comment by imShara** [comment]
Thank you for the time. Could it be fixed with slots?

Something like this:

**`l-marker`**

````vue
<script setup>
import { useSlots } from 'vue'
const slots = useSlots()
</script>

<template>
  <slot name="icon" v-if="slots.icon"/>
  <i v-else>I'm a default icon</i>
</template>

**Comment by lukkyjoe** [comment]
Hi @imShara and @mikeu , 
I took a look at this issue out of curiosity, and while I am able to reproduce the blinking marker in cases where the vue-leaflet npm package is imported into an app, I could not reproduce the issue in the playground of the npm package repo itself. 
Could this be a case where it's not even an issue with application logic...?!
Also @imShara , regarding your suggestion to fix with slots, doesn't the LMarker logic already do that here? https://github.com/vue-leaflet/vue-leaflet/blob/master/src/components/LMarker.vue#L66

**Comment by imShara** [comment]
> the blinking marker in cases where the vue-leaflet npm package is imported into an app,

I think because it loads default styles with marker icons

**Comment by imShara** [comment]
>  doesn't the LMarker logic already do that here?

It loads content with slot, but there is unclean extra logic especially for markers

**Comment by mikeu** [comment]
> It loads content with slot, but there is unclean extra logic especially for markers

@imShara do you have an example of what specifically you think is unclean and extra in the slot/render logic for markers?
