### ISSUE TITLE
Gray Tile No Map

### ISSUE THREAD

**Issue by aminmooridev** [vue-leaflet/vue-leaflet#189]
Hi. I have a problem. when i use leaflet on quasar framework. leaflet doesn't work. but i don't know why? somebody help me please.

![Captdsadsaure](https://user-images.githubusercontent.com/58544408/152529237-00ee4968-ad43-45cc-b4c1-6d27a0520c88.PNG)

![Captursdadae](https://user-images.githubusercontent.com/58544408/152529256-6ed165c2-87ed-4332-b386-48be88bd2b8c.PNG)

**Comment by lrstanley** [comment]
@aminmooridev did you ever figure the issues out?

**Comment by hbsoftco** [comment]
This issue is related to RTL direction. You should set the parent `<div>` of the map to LTR direction.
