### ISSUE TITLE
Create polygon with map click event

### ISSUE THREAD

**Issue by noxyz20** [vue-leaflet/vue-leaflet#195]
Hi ! I would like to be able to create l-polygon when the map is clicked. I have already done it for markers but it doesn't work with l-polygon even though the "lat" and "lng" data are well registered.

```
<l-map style="height:50vh;width=25%" @click="addMarker($event)" :center="[42.309410, 	9.149022]" :zoom="14">
      <l-polygon :lat-lngs="polygon" color="#41b782" :fill="true" :fillOpacity="0.5"  fillColor="#41b782" />               
</l-map>
```
```
data() {
    return {
      zoom: 2,
      polygons: [],
    }
  },
methods: {
    addMarker(event) {
       this.polygons.push([event.latlng.lat, event.latlng.lng]);
   }
}
```

output : 
![Capture d’écran du 2022-03-01 11-52-27](https://user-images.githubusercontent.com/33814441/156156288-17daa13b-30d0-450d-9371-1edc0ca71d0b.png)

Thx !

**Comment by entioentio** [comment]
Isn't it because of a typo? You have `<l-polygon :lat-lngs="polygon"` whilst your component's variable is named `polygons`

**Comment by noxyz20** [comment]
Hey ! ty for your reply,
I solved my problem by forcing a refresh on my commponent **l-polygon** with a **v-if** directive

**Comment by entioentio** [comment]
Check. You might as well want to close the issue 🙃

**Comment by noxyz20** [comment]
ofc thx
