### ISSUE TITLE
No leaflet folder when add leaflet library

### ISSUE THREAD

**Issue by iroshiva** [vue-leaflet/vue-leaflet#225]
Hi !

On a vuejs/vite project, i ran `$ yarn add @vue-leaflet/vue-leaflet` and tried to import the css `import "leaflet/dist/leaflet.css"` in a component.

I get an error: `Failed to resolve import "leaflet/dist/leaflet.css"`

After looking in the node_modules folder, there's no folder 'leaflet'.

Why there's no 'leaflet' folder for the css ?
Did i miss something ?

Thx

**Comment by harryspink** [comment]
You need to use npm to install leaflet.

`npm i leaflet`

**Comment by mikeu** [comment]
Hi @iroshiva ! Leaflet is set as a peer dependency of vue-leaflet, so if you have not installed it yourself then you should be seeing errors in your console about "unmet peer dependencies". As harryspink said, the simple solution is to add whichever version of Leaflet you want to work with to the project as well:

`yarn add leaflet`
