### ISSUE TITLE
breaking changes leaflet 1.9.2

### ISSUE THREAD

**Issue by mpDevAB** [vue-leaflet/vue-leaflet#236]
Hello. I use this package in two diferent applications. One was working fine but a new install on another app (using exactly same code as first app) this package breaks. I tracked it down to that leaflet 1.9.2 is not working with this package (0.6.1). Downgrading leaflet to 1.8.0 works

I was getting L is not defined with 1.9.2

**Comment by joelmandell** [comment]
Interesting. I thought it was only me doing something stupid

**Comment by nilloq** [comment]
Hello, I confirm I encounter the same issue

**Comment by xoxefdp** [comment]
You sure its not related to the way you import leaflet?
TRY -> import * as L from 'leaflet/dist/leaflet-src.esm'
INSTEAD OF -> import L from 'leaflet'

**Comment by joelmandell** [comment]
@xoxefdp I am only importing the components.

**Comment by HannesOberreiter** [comment]
Same error, it works with version 1.9.1. It could be a problem with the import, which is a breaking change:

https://github.com/Leaflet/Leaflet/releases/tag/v1.9.2

**Comment by ajmas** [comment]
@m[mpDevAB](https://github.com/mpDevAB) do you have a sample project that demonstrates the issue? It would be easier to understand the issue once seen in context.

**Comment by ajmas** [comment]
Looking at the issues in the leaflet repo, I am seeing [this comment](https://github.com/Leaflet/Leaflet/discussions/7729#discussioncomment-1576995), which suggests a breaking change, but because there are no examples of leaflet being used as a module, it is not clear how this should be addressed.

**Comment by mikeu** [comment]
Thank you all for the reports and discussion around this issue. Leaflet is now on v1.9.3 and I would be curious to hear if there are any specific problems caused in vue-leaflet by that release. However, since Leaflet is a peer dependency of this library exactly so that you are free to select whichever version works for you, I don't think this is anything that requires a specific fix to vue-leaflet.

**Comment by rafaellehmkuhl** [comment]
> Thank you all for the reports and discussion around this issue. Leaflet is now on v1.9.3 and I would be curious to hear if there are any specific problems caused in vue-leaflet by that release. However, since Leaflet is a peer dependency of this library exactly so that you are free to select whichever version works for you, I don't think this is anything that requires a specific fix to vue-leaflet.


Leaflet v1.9.3 solves the problem of receiving "L is not defined" when adding an LPopup.
