### ISSUE TITLE
A property "options-style" is not working in a component LGeoJson

### ISSUE THREAD

**Issue by kasumi-ibe-kbt** [vue-leaflet/vue-leaflet#258]
Hello there,

The property "options-style" can be used in Vue2Leaflet LGeoJson, but it is not working in vue3 ver.
I'm thinking it's useful if I can use the property though, are there any reason to decide to abolish the property?

**Comment by ismanfromes** [comment]
Major problem for the project I'm currently working on.
The project was initially created with **Vue2 + Vue2Leaflet** but had to be upgraded to Vue3.
_I have been looking for alternatives but haven't found any yet.._

**Comment by mikeu** [comment]
Hi @kasumi-ibe-kbt , thank you for the suggestion! There was no explicit choice to remove the `options-style` property, it just got missed at some point and we didn't realize it wasn't there. I have just released [v0.8.3](https://github.com/vue-leaflet/vue-leaflet/releases/tag/v0.8.3), which re-introduces the property. Please let me know if you run into any further issues with it!
