### ISSUE TITLE
Geoman integration with Vue3 Leaflet

### ISSUE THREAD

**Issue by scramatte** [vue-leaflet/vue-leaflet#260]
Hello,

I've searched into existing issues if somebody has solved the problem to integrate geoman with vue3 leaftlet.
I've tried various things without success.

The last I test is the example of #90  issue but it tell me that map.pm is undefined so I can't add controls.
Does it possible to post a functional example here?

Regards

**Comment by mikeu** [comment]
Hi @scramatte , I have a [codesandbox vue-leaflet/geoman demo](https://codesandbox.io/s/vl-geoman-rig1vj?file=/src/App.vue) that I just updated to use v0.7.0 of vue-leaflet. Hopefully that is enough to get you going, and let me know if you have any questions or issues with it!

**Comment by scramatte** [comment]
I'm trying to integrate into laravel Nova 4  as custom tool  and I've got same error.

![image](https://user-images.githubusercontent.com/188766/212210599-185f8c01-3c15-489c-acd5-28371f0d2771.png)

I can't check your codesand due to an error on their platform

![image](https://user-images.githubusercontent.com/188766/212210520-abd81715-ae5f-4f67-bd89-72a6bb540009.png)

**Comment by scramatte** [comment]
Thank you very much, it works. I don't know why but depiste exec "npm update" it was still  use vue-leaflet 0.6 
I've force to use  0.7 and now it works.

**Comment by minzdrav** [comment]
doesn't work with 0.8.2

**Comment by mikeu** [comment]
@minzdrav do you have any sort of information at all about the way in which it doesn't work? Could you also try it with the latest version, 0.8.3, and let me know if you're still having issues there?

**Comment by minzdrav** [comment]
> @minzdrav do you have any sort of information at all about the way in which it doesn't work? Could you also try it with the latest version, 0.8.3, and let me know if you're still having issues there?

Hi @mikeu 
Error: mapObject.value.pm is undefined
Fork with 0.8.3: https://codesandbox.io/s/vl-geoman-forked-x79dhz
![image](https://user-images.githubusercontent.com/1764392/220069979-cbb177ce-4441-4577-978c-a11ca872ff72.png)

**Comment by mikeu** [comment]
Thanks @minzdrav ! You can resolve that issue on 0.8.3 by explicitly setting `:use-global-leaflet="true"` on your LMap component, or by updating to [0.8.4](https://github.com/vue-leaflet/vue-leaflet/releases/tag/v0.8.4) which I've just released.

**Comment by minzdrav** [comment]
Hi @mikeu 
Thank you. Super-fast fix!
