### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Default')

### ISSUE THREAD

**Issue by HamzaAdam** [vue-leaflet/vue-leaflet#279]
Unable to run package with laravel valet due to missing declaration of module.
I am getting this error
Could not find a declaration file for module '@vue-leaflet/vue-leaflet'. '/Users/.../.../.../node_modules/@vue-leaflet/vue-leaflet/dist/vue-leaflet.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue-leaflet__vue-leaflet` if it exists or add a new declaration (.d.ts) file containing `declare module '@vue-leaflet/vue-leaflet';

**Comment by HamzaAdam** [comment]
My package.json looks like this:
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@inertiajs/vue3": "^1.0.0",
        "@tailwindcss/forms": "^0.5.3",
        "@types/google.maps": "^3.51.1",
        "@vitejs/plugin-vue": "^4.0.0",
        "@vue-leaflet/vue-leaflet": "^0.8.4",
        "autoprefixer": "^10.4.12",
        "axios": "^1.1.2",
        "laravel-vite-plugin": "^0.7.2",
        "leaflet": "^1.9.3",
        "lodash": "^4.17.19",
        "postcss": "^8.4.18",
        "tailwindcss": "^3.2.1",
        "vite": "^4.0.0",
        "vue": "^3.2.41"
    },
    "dependencies": {
        "@googlemaps/js-api-loader": "^1.15.1"
    }
}

I am using laravel valet to run development environment and vite plugin for bundling frontend code.
The leaflet is working good if I run the command "npm run build" but with "npm run dev" leaflet is not working.
@mikeu Do you have any solution.

**Comment by Rifaldikn** [comment]
i have same problem here

<img width="463" alt="image" src="https://github.com/vue-leaflet/vue-leaflet/assets/22056556/2c890005-3598-43b5-a964-630b614c83ec">
