### ISSUE TITLE
Heatmap overlay

### ISSUE THREAD

**Issue by ltrojan** [vue-leaflet/vue-leaflet#283]
is there any way a heatmap can be added over the map?

there's an example using `leaflet.heat` and the Leaflet Heatmap Overlay package from Patrick Wied [website](https://www.patrick-wied.at/static/heatmapjs/) on code sandbox: [code sandbox example](https://codesandbox.io/s/iojw4?file=/src/App.vue)

that example uses the vue2 version, is there anything similar for vue3?

I know this is not really an "issue"... can anyone point me to the best place to ask this question?

thanks!

**Comment by mikeu** [comment]
Hi @ltrojan , I'm sorry to say that at the moment the best reference I'm aware of for creating your own vue-leaflet plugin for `leaflet.heat` would be primarily to look at how we instantiate and add to a map the core components, e.g. in `components/LTileLayer.vue` and the corresponding `functions/tileLayer.ts`. If there is a Vue2Leaflet plugin for the same, then much of the logic is similar and its methods might also be of some help.

If you do publish a plugin for these, please let us know so it can be referenced from here!
