### ISSUE TITLE
Click event not working with 0.9.0

### ISSUE THREAD

**Issue by harm-matthias-harms** [vue-leaflet/vue-leaflet#287]
The `@click` handler of the LMap component is not returning a `LeafletMouseEvent` anymore. Thus, we cannot call methods/fields, like `latlng`, anymore on the event.

I was able to reproduce the bug in this example: https://stackblitz.com/edit/vue-leaflet-click-bug?file=app.vue

**Comment by mikeu** [comment]
Thanks for reporting this @harm-matthias-harms , that's a weird one! Off the top of my head I can't think of anything in the conversion to typescript that would have changed the pass-through behaviour of Leaflet events. I'll take a deeper look into it over the next couple of days and hopefully have a fix out soon. In the meantime, hopefully an earlier version continues to work for you while the conversion to TypeScript gets further ironed out.

**Comment by Vectorial1024** [comment]
Hi there, is there any schedule to fix this? It is nice to see 0.9.0 finally getting some proper Typescript support, but this bug has basically made the library unusable.

**Comment by lindaifu** [comment]
[# 179](https://github.com/vue-leaflet/vue-leaflet/issues/179#issuecomment-1600265884)

get map instance in "ready" function

const onMapReady = (mapIns)=>{
mapIns.on('click', (ev)=>{
console.log('click', ev)
})
}

<LMap @ready="onMapReady">
