### ISSUE TITLE
Is it possible to pass in options as an object, what about unsupported options such as zoomSnap and zoomDelta?

### ISSUE THREAD

**Issue by vesper8** [vue-leaflet/vue-leaflet#290]
I want to make use of 

```

var map = L.map('map', {
    zoomDelta: 0.25,
    zoomSnap: 0
});
```

https://leafletjs.com/examples/zoom-levels/

It appears to me like these custom options are not supported by vue-leaflet because they are not specifically available in the LMap component.

Is there any way of using this options short of forking this repo?

many thanks!

**Comment by vesper8** [comment]
I was able to get around it like this

```

      onReady() {
        this.$nextTick(() => {
          this.map = this.$refs.map.leafletObject;

          this.map.options.zoomDelta = 0.5;
          this.map.options.zoomSnap = 0;

          this.renderMap();
        });
      },
```

Now I'm scratching my head as to why it won't accept a starting zoom value of -1.5, it seems no matter what I do is defaults to -1

**Comment by mikeu** [comment]
Hi @vesper8 , you should be able to just pass them as options on the map, as in
```vue
<l-map :options="{ zoomDelta: 0.25, zoomSnap: 0 }" ...>
```
The only thing not specifically available for them on the LMap component is reactivity, so updating the delta and snap later won't actually change the underlying map. Please let me know if that doesn't work for you!
