### ISSUE TITLE
l-routing-control

### ISSUE THREAD

**Issue by Hodadisbirhan** [vue-leaflet/vue-leaflet#293]
How could I use the l-routing-control in leaflet-routing-machine plugin with the @vue-leaflet/vue-leaflet plugin

**Comment by mikeu** [comment]
Hi @Hodadisbirhan , most Leaflet plugins are created and added to a map very similarly to how the core components are. Perhaps looking at a component such as components/LPolygon.vue and its corresponding functions/polygon.ts would be a good place to start. It's a fairly common pattern throughout most of the components, and should hopefully be quite similar for most other Leaflet plugins as well.

**Comment by Hodadisbirhan** [comment]
Thank you It works well
