### ISSUE TITLE
[Feature Request] Is it possible to have some kind of @onOpen @onClose on the l-popup ?

### ISSUE THREAD

**Issue by vesper8** [vue-leaflet/vue-leaflet#295]
I have a lot of custom UI elements in the corners of my map and I noticed that when a popup is opened from clicking a marker, the popup often clashes with the map's UI elements on small mobile devices, so I would like to hide all those UI elements whenever a popup is visible, and then show them again when the popup is closed. Are there any events that I can listen to on the l-popup component that would allow me to easily accomplish this?  Otherwise, is there another convenient way to do it with a vanilla js listener?

Many thanks!

**Comment by mikeu** [comment]
Hi @vesper8 , the `@popupopen` and `@popupclose` events on the marker that has the popup should be what you're looking for I think. Something like
```vue
<l-marker :lat-lng="markerPos" @popupopen="hideUI" @popupclose="showUI">
  <l-popup> Hello, map! </l-popup>
</l-marker>
```

**Comment by vesper8** [comment]
Thank you! That's exactly what I needed!
