### ISSUE TITLE
Playground doesn't work

### ISSUE THREAD

**Issue by dimka11** [vue-leaflet/vue-leaflet#298]
173/src/playground/index.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)

Where I can get index.js file? In direcory only the .ts file

**Comment by mikeu** [comment]
Hi @dimka11 , thank you for pointing this out! The problem was not that the js file wasn't there, but that the index.html was looking for it instead of the TypeScript one.

I've just pushed an update to `master` that should get the playground up and running for you if you pull the latest.
