### ISSUE TITLE
Show markers in cluster if zoomed out

### ISSUE THREAD

**Issue by martinsagat** [vue-leaflet/vue-leaflet#302]
How can I display multiple markers in a cluster? Has this been implemented?

**Comment by AbdullahSohail-SE** [comment]
@martinsagat i was wondering the same, have you been able to find a solution to this?

**Comment by veitbjarsch** [comment]
I created a markercluster plugin for vue-leaflet. https://github.com/veitbjarsch/vue-leaflet-markercluster

It is currently an alpha version, so every feedback would be welcome.

**Comment by mikeu** [comment]
Hi @martinsagat , since this functionality is not part of Leaflet itself, we won't be adding it to vue-leaflet either. Awesome to see @veitbjarsch has started a plugin for it though, thanks for that!
