### ISSUE TITLE
Add support for `L.Donut`

### ISSUE THREAD

**Issue by Bassadin** [vue-leaflet/vue-leaflet#307]
https://github.com/Falke-Design/L.Donut

This repository added a leaflet component called `L.Donut`, which would be pretty useful for my current problem. Would it be possible to add it to this project? I'd love to help implementing/contributing, but I don't know where to start.

Keep up the awesome work!

**Comment by mikeu** [comment]
Hi @Bassadin , thank you for your support and suggestion! Unfortunately, the goal of this project is to provide only the core functionality of Leaflet itself in Vue components. If you were to create a vue-leaflet plugin corresponding to that Leaflet plugin, then we wouldhappily reference it from our repo, but we won't be adding it directly to this library.

Better documentation and support around plugin creation is on our roadmap, but still a ways out I'm afraid. In the meantime, most Leaflet plugins are create and added to a map very similarly to how the core components are. Perhaps looking at a component such as `components/LPolygon.vue` and its corresponding `functions/polygon.ts` would be a good place to start. It's a fairly common pattern throughout most of the components, and should hopefully be quite similar for `L.Donut`.

If you do start down that path and have some more specific questions, please do come and add them here, or start a [discussion](https://github.com/vue-leaflet/vue-leaflet/discussions) about the topic!

**Comment by Bassadin** [comment]
@mikeu I will try, thanks :) Would I be uploading that plugin to its own GitHub repo then? Is there a similar repo that I can use as a reference?

**Comment by mikeu** [comment]
@Bassadin you totally could if you wanted to share it back to the community :) Unfortunately, I'm not aware of any other plugins for vue-leaflet itself at the moment (which would mean you'd be the first). There are plenty of [Vue2Leaflet plugins](https://vue2-leaflet.netlify.app/plugins/) though, which combined with the patterns in component pairs here (e.g. `LPolygon.vue` and `polygon.ts`) will hopefully get you a lot of the way there!

**Comment by Bassadin** [comment]
I hope I'll have time for it in a few months :)
