### ISSUE TITLE
vite + vue3 + vue-leaflet：LMap doesn't work.

### ISSUE THREAD

**Issue by lindaifu** [vue-leaflet/vue-leaflet#312]
vite + vue3 + vue-leaflet：LMap doesn't work.

vite ^3.1.0
vue ^3.2.37

don't render
`
leaflet ^1.9.4
@vue-leaflet/vue-leaflet ^0.9.0
`

this config is ok
`
leaflet ~1.6.0
@vue-leaflet/vue-leaflet ~0.6.0
`

perhaps other versions can also be used

**Comment by stsposoh** [comment]
Try to add :useGlobalLeaflet="false" to your <LMap></ LMap>

**Comment by cerw** [comment]
See https://github.com/vue-leaflet/vue-leaflet/issues/278

**Comment by mikeu** [comment]
Duplicated in #278
