### ISSUE TITLE
Publish v0.10.0 to npm

### ISSUE THREAD

**Issue by 1Luc1** [vue-leaflet/vue-leaflet#318]
@mikeu Thanks for your new release. May you publish the new version v0.10.0 to npm registry?

**Comment by mikeu** [comment]
@1Luc1 absolutely, thank you for letting me know! I missed that the pipeline didn't publish it, will look into why next week but for now you should be able to use v0.10.0 and v0.10.1 (with `Utilities` exported) from NPM now.
