### ISSUE TITLE
LMap.zoomControl=false not implemented

### ISSUE THREAD

**Issue by dcolley** [vue-leaflet/vue-leaflet#321]
I can't disable or reposition the default zoom controls.

```vue
    <l-map ref="map"
      v-model:zoom="zoom"
      :center="[47.41322, -1.219482]"
      :use-global-leaflet="false"
      preferCanvas="true"
      :world-copy-jump="false"
      :maxBounds="[[[90,-200],[-90,200]]]"
      :max-bounds-viscosity="1"
      :control-zoom="false"
      :zoom-control="false"
      >
      <l-tile-layer
        url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
        layer-type="base"
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
        subdomains='abcd'
        :maxZoom="maxZoom"
        :minZoom="minZoom"
        name="OpenStreetMap"
      ></l-tile-layer>
      <l-control-zoom position="bottomright"></l-control-zoom>
    </l-map>
```
<img width="812" alt="image" src="https://github.com/vue-leaflet/vue-leaflet/assets/1845970/c627960b-231e-4933-9f5c-bfa182ce3a1b">

Eg: https://stackoverflow.com/questions/33614912/how-to-locate-leaflet-zoom-control-in-a-desired-position

**Comment by dcolley** [comment]
it seems adding this to the map works:

```
:options="{ zoomControl: false, attributionControl: false }"
```

**Comment by mikeu** [comment]
@dcolley yes, for many options that Leaflet does not allow to be changed after instantiation, the intended approach to passing them is to use the `:options` prop object. This also allows new options to be used as soon as Leaflet adds them, without requiring a corresponding update to vue-leaflet.
