### ISSUE TITLE
No access to leaflet object with nuxt 3

### ISSUE THREAD

**Issue by lud-hu** [vue-leaflet/vue-leaflet#337]
Hi,

I've scanned through a lot of documentation and issues but I cannot get nuxt3 together with vue-leaflet to work.

I've set the `:use-global-leaflet="false"` flag, added the `leaflet: path.join(__dirname, "node_modules/leaflet")` to the nuxt config alias and tried to access the leafletObject in `this.$nextTick(() => {}` but it's still not working:

```
Cannot read properties of undefined (reading 'fitBounds')
```

![image](https://github.com/vue-leaflet/vue-leaflet/assets/26108368/77e17544-6d44-4360-a9a0-255b48d07319)

Minimal reproduction repo:
https://github.com/lud-hu/nuxt-leaflet-object-reproduction

And by the way: How can I access the map ref with vue3's composition API (so without the export default...)?

**Comment by lud-hu** [comment]
I finally found a way to properly handle it with nuxt3 and composition API.
I've pushed it to this branch: https://github.com/lud-hu/nuxt-leaflet-object-reproduction/blob/fix/app.vue

```ts
<template>
    <client-only>
        <div class="map-wrapper">
            <l-map ref="map" :center="[47.41322, -1.219482]" :use-global-leaflet="false" @ready="init">
                <l-tile-layer
                    url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                    layer-type="base"
                    name="OpenStreetMap"
                ></l-tile-layer>
            </l-map>
        </div>
    </client-only>
</template>

<script lang="ts" setup>
import "leaflet/dist/leaflet.css";
import type L from "leaflet";

import { LMap, LTileLayer } from "@vue-leaflet/vue-leaflet";

const map = ref<any>();

const init = () => {
  if (map) {
    map.value.leafletObject.fitBounds([[47.41322, -1.219482], [47.51322, -1.319482]]);
  }
};
</script>
```

My main problem actually was when trying the @ready before, that the IDE always changed it to on-ready. But I don't know if it's a library specific problem or if the vue IDE plugin is just not clever enough yet.

Hope it saves some time for others... 😄

**Comment by lagamura** [comment]
thank you for documenting that @lud-hu, you really saved us some time!

**Comment by lagamura** [comment]
By the way, let me add one question: is there a type for leaflet object instead of using ref<any>() so we can get type suggestions and function documentation?
