### ISSUE TITLE
Integration with Leaflet Geoman plugin

### ISSUE THREAD

**Issue by juan267** [vue-leaflet/vue-leaflet#35]
Hello, thanks for all your hard work. 

I have been doing some prototypes using the Vue 3 repo recently and everything was working perfect until I wanted to install https://github.com/geoman-io/leaflet-geoman . 

This plugin auto install itself on the L constant when it  it's imported. The current Vue 3 components for what I can see are dynamically importing leafleat so I haven't found a way to make the plugin be able to reference the same leaflet map object that the component is using. 

I try doing things similar to https://github.com/geoman-io/leaflet-geoman/issues/580 but given the new way that the Vue 3 library works with leaflet it's not working for me. Any help is very much appreciated! thanks

**Comment by Falke-Design** [comment]
If there is anything needed from Geoman to solve this? We are happy to help

**Comment by juan267** [comment]
@Falke-Design I think that having an option to not auto initialize Leaflet geoman would help. That way we can wait until the component map leaflet object from vue-leflet is ready and then manually initialize geoman on it.

**Comment by Falke-Design** [comment]
Have you an example how this can look like? I think it will not easy to remove it.

@codeofsumit FYI

**Comment by codeofsumit** [comment]
Wouldn't that be possible with conditional/async imports? Require Leaflet-Geoman only once leaflet is loaded?

@juan267 could you provide a JSfiddle with the setup you're trying to use here? Happy to look for solutions here

**Comment by juan267** [comment]
@codeofsumit @Falke-Design thanks for your help here 🙇  I try recreating an example on JSfiddle but it's not easy because `@vue-leaflet/vue-leaflet` can not be added via CDN. I also try creating a codesandbox here https://codesandbox.io/s/dazzling-morning-u3irq?file=/src/App.vue but for some reason is breaking when I add the `leaflet` dependency. 

So for now I will just leave the code that  Im currently trying to make work

```vue
<template>
  <div style="height: 50vh; width: 50vw;">
    <l-map
      ref="map"
      v-model="zoom"
      v-model:zoom="zoom"
      :center="[47.41322, -1.219482]"
    >
      <l-tile-layer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      ></l-tile-layer>
      <l-marker :lat-lng="[0, 0]" draggable></l-marker>
    </l-map>
  </div>
</template>

<script lang="ts">
import @geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css'
import { defineComponent, ref, onMounted, nextTick } from 'vue'
import { LMap, LTileLayer, LMarker } from '@vue-leaflet/vue-leaflet'
import L, { Map } from 'leaflet'
import 'leaflet/dist/leaflet.css'

export default defineComponent({
  components: {
    LMap,
    LTileLayer,
    LMarker
  },
  setup() {
    const map = ref<null | { mapObject: Map }>(null)
    onMounted(() => {
      nextTick(async () => {
        // mapObject here is the leaflet map instance but because of Vue3 is behind a Proxy I don't know if that might have an impact
        // I need geoman to get installed on this leaflet map instance, So I try creating  the L const here based on it. But it's not working
        const L = map.value?.mapObject
        console.log(L)
        await import('@geoman-io/leaflet-geoman-free')
      })
    })

    return { map }
  },
  data() {
    return {
      zoom: 2
    }
  }
})
</script>
```

**Comment by codeofsumit** [comment]
@juan267 does that script work?

**Comment by juan267** [comment]
@codeofsumit  it does not :( 

It appears that codesandbox fix their error installing leaflet so here you can play with demo of it. https://codesandbox.io/s/adoring-violet-q2q4p?file=/src/App.vue

This is the current code that Im trying but it's also not working 

```vue
<template>
  <div style="height: 50vh; width: 50vw">
    <l-map
      ref="map"
      v-model="zoom"
      v-model:zoom="zoom"
      @ready="mapReady"
      :center="[47.41322, -1.219482]"
    >
      <l-tile-layer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      ></l-tile-layer>
      <l-marker :lat-lng="[0, 0]" draggable></l-marker>
    </l-map>
  </div>
</template>

<script>
import "@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css";
import { ref, onMounted, nextTick } from "vue";
import { LMap, LTileLayer, LMarker } from "@vue-leaflet/vue-leaflet";
import "leaflet/dist/leaflet.css";

export default {
  name: "App",
  components: {
    LMap,
    LTileLayer,
    LMarker,
  },
  setup() {
    const map = ref(null);

    const mapReady = async () => {
      window.L = map.value.leafletObject;
      console.log(L);
      await import("@geoman-io/leaflet-geoman-free");
      L.pm.addControls({
        position: "topleft",
        drawCircle: false,
      });
    };

    return { map, mapReady };
  },
  data() {
    return {
      zoom: 2,
    };
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

**Comment by Falke-Design** [comment]
I'm not a vue coder, so I can't really help. But maybe the code from other projects help you https://github.com/search?l=Vue&q=Geoman+type%3DVue&type=Code

**Comment by codeofsumit** [comment]
@juan267 in your `mapReady` method, replace `L.pm.addControls` with `map.pm.addControls`.

I'm not 100% familiar with vue 3 so even though I don't see where the `map` object is defined, I expect `map` is an available reference to your leaflet map inside `mapReady`.

After you have done that, what error are you getting?

**Comment by juan267** [comment]
@codeofsumit  If you do this ```replace L.pm.addControls with map.pm.addControl``` you get the following error

<img width="669" alt="Screen Shot 2020-11-03 at 9 09 03" src="https://user-images.githubusercontent.com/8763740/97995219-3bd3ff00-1db4-11eb-9358-689abde463b5.png">

What's happening here is that the `l-map` component when it's mounted it does the following: 

```js
  onMounted(async () => {
      const {
        map,
        CRS,
        Icon,
        latLngBounds,
        latLng,
        DomEvent,
        setOptions,
      } = await import("leaflet/dist/leaflet-src.esm");
       
      // Creates the leaflet object here 
      blueprint.leafletRef = map(root.value, options);

    const leafletObject = computed(() => blueprint.leafletRef);
    const ready = computed(() => blueprint.ready);
  }

    // Makes the leafletObject available on the `l-map` instance
    return { root, ready, leafletObject };
}
```

Later as a user of `vue-leaflet` you would mount the `l-map` component inside a parent component like this: 

```vue
<template>
  <div style="height: 50vh; width: 50vw">
    <l-map
      ref="map"
      v-model="zoom"
      v-model:zoom="zoom"
      @ready="mapReady"
      :center="[47.41322, -1.219482]"
    >
      <l-tile-layer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      ></l-tile-layer>
      <l-marker :lat-lng="[0, 0]" draggable></l-marker>
    </l-map>
  </div>
</template>
```

At this point the leaflet map is being rendered correctly, and because of the way the `l-map` works there's no `L` constant available on `window` the reference to the leaflet object being used must be accessed in the following way: 

```js
    const mapReady = async () => {
      // This is the leaflet object being used by l-map
      map.value.leafletObject;
    };
```

The problem with `Geoman` is that it makes some assumptions on how the leaflet object must exists on the page.

- It assumes that the `L` constant most be present on window
- The `L` constant is a reference to the active leaflet object being used for map rendering

As you can see with `vue-leaflet` this two assumptions don't hold. So one way to fix this issue would be to change the way that `Geoman` gets initialize. 

Inside `leaflet-geoman/src/js/L.PM.js ` lines [40](https://github.com/geoman-io/leaflet-geoman/blob/4fc91ec99f1206221d062d6945eeb3fe5fdcf4bf/src/js/L.PM.js#L40) to 159 could be wrapped into a function that could be call `createGeoman` 

after that users could do something like 

```js
import { createGeoman }  from "@geoman-io/leaflet-geoman-free")

// manually initialize geoman and pass the leaflet object reference 
    const mapReady = async () => {
      // Here I can pass the leaflet object that I want to use
      geoman = createGeoman({ L: map.value.leafletObject;}) 
      
      // This would be the analogous to what's happening on line 162 in leaflet-geoman/src/js/L.PM.js
      geoman.initialize()
    };
```

This way `Geoman` gives users the option to initialize itself on any leaflet object without making assumptions on how leaflet object should exists on users applications. 

Let me know what you think of this approach and if it's possible to implement. I would also be happy to help writing the code

**Comment by codeofsumit** [comment]
Mhh yes I think we can do something like this on our end but I do not understand why `window.L = map.value.leafletObject;` is not fixing this. At the time of importing Leaflet-Geoman, L should be present on the window object, no?

**Comment by juan267** [comment]
>  At the time of importing Leaflet-Geoman, L should be present on the window object, no?

Yeah I would have supposed the same but for some reason is not working 😕 I get the following error: 

<img width="467" alt="Screen Shot 2020-11-04 at 14 16 09" src="https://user-images.githubusercontent.com/8763740/98158113-6d2df700-1ea8-11eb-84db-9fdc5dcdd6f3.png">

**Comment by mechevarria** [comment]
Just for everyone looking for a basic example of integration of vue-leaflet and geoman, I have an example here with vue2

[https://github.com/mechevarria/demo-vue-leaflet-geoman/blob/master/src/components/Map.vue](https://github.com/mechevarria/demo-vue-leaflet-geoman/blob/master/src/components/Map.vue)

**Comment by juan267** [comment]
@mechevarria Thanks but the issue here is with `vue-leaflet` which is the new version for `Vue 3`. `'vue2-leaflet'` for vue 2 works fine as it's demonstrated on your example.

**Comment by DonNicoJs** [comment]
I've recently got geoman working with vue-leaflet, I'll be creating a plugin for it real soon! I will post an update here for this.

The trick is to correctly `bind` the `esm leaflet` to the window and geoman.
