### ISSUE TITLE
TypeError: e is undefined

### ISSUE THREAD

**Issue by prpanto** [vue-leaflet/vue-leaflet#373]
I didn't had problem with previews version of nuxt.

I think the problem is in this function [here](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/src/utils.ts#L99) and basicaly this line [here](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/src/utils.ts#L106C3-L106C9)  basic of the firefox debugger.

<br>

code from firefox debugger:
```js
const o = await Promise.all([
  import("leaflet/dist/images/marker-icon-2x.png"),
  import("leaflet/dist/images/marker-icon.png"),
  import("leaflet/dist/images/marker-shadow.png")
]);
----HERE---> delete e.Default.prototype._getIconUrl, e.Default.mergeOptions({
  iconRetinaUrl: o[0].default,
  iconUrl: o[1].default,
  shadowUrl: o[2].default
});
```

**Comment by cradcore** [comment]
@prpanto Were you able to fix this? I am getting this error and not sure how to resolve it

**Comment by Parivan** [comment]
Same error. Any solution?
@prpanto @cradcore

**Comment by Parivan** [comment]
I solve this.
Add :useGlobalLeaflet="false" proprerty.

```vue
        <l-map ref="map" v-model:zoom="zoom" :center="[47.41322, -1.219482]" :useGlobalLeaflet="false">
            <l-tile-layer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                layer-type="base"
                name="OpenStreetMap"
            ></l-tile-layer>
        </l-map>
```
