### ISSUE TITLE
Smooth zoom

### ISSUE THREAD

**Issue by ManUtopiK** [vue-leaflet/vue-leaflet#83]
Thanks for your work!
I noticed zooming the map is different than vue2-leaflet. There is no smooth transition between each zoom level.
Each tiles flash with a gray overlay. In vue2-leaflet, the tiles scale up or down and fade with the next zoom level.
I think it's not a normal behavior...

**Comment by Saltibarsciai** [comment]
it's no longer default behaviour, now try to add `zoomAnimation = true` on map: 

```
<l-map :zoomAnimation="true"></lmap> 
```

**Comment by ManUtopiK** [comment]
Yeah it's better like that! 😃 
Thanks.

**Comment by ManUtopiK** [comment]
Are there any reason to change default leaflet values? `zoomAnimation` [default value is true](https://leafletjs.com/reference-1.7.1.html#map-zoomanimation).

**Comment by Saltibarsciai** [comment]
I guess it's forgotten that leaflet had default one.
@DonNicoJs @mikeu is it intentional, maybe it was too bloated before?
