### ISSUE TITLE
Could not find a declaration file for module '@vue-leaflet/vue-leaflet'

### ISSUE THREAD

**Issue by KhaledOmara** [vue-leaflet/vue-leaflet#84]
I'm trying to import the module by I got
```
Could not find a declaration file for module '@vue-leaflet/vue-leaflet'. '/media/khaledomara/Data/Work/00 - EgyProTech/00 - GitLab/03- Android Apps/ePowerDMS Drivers/ePowerDMS-Driver/node_modules/@vue-leaflet/vue-leaflet/dist/vue-leaflet.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue-leaflet__vue-leaflet` if it exists or add a new declaration (.d.ts) file containing `declare module '@vue-leaflet/vue-leaflet';`Vetur(7016)
```
I'm using typescript

**Comment by mikeu** [comment]
Hi @KhaledOmara , thank you for reporting this! At the moment we do not have typescript support in the library, but we are planning to add it eventually, as discussed in #1.

**Comment by scholtz** [comment]
any update on this? it has been here for more than 2 years..

**Comment by InsHomePgup** [comment]
It's resolved? I have a leaflet components needs props , but i don't know how to import types.
