### ISSUE TITLE
Tile layer minZoom and maxZoom

### ISSUE THREAD

**Issue by AntoninRousset** [vue-leaflet/vue-leaflet#91]
Just started using vue-leaflet and it works great! (:
I couldn't set the `minZoom` and `maxZoom` of a `l-tile-layer`, although it works nicely with the `l-map`.
I went through the code and this seems to be the desired behaviour. I used however to set these options to be able to load more images as I zoom in... what do?

**Comment by mikeu** [comment]
Hi @AntoninRousset , thank you for reporting this issue! Looks to me as if you are correct at the moment, those options are simply not part of the current vue-leaflet API. This is more of an oversight in the early version of the Vue 3 update, than a design choice though. I'll try to push a PR to add that feature soon!

**Comment by AntoninRousset** [comment]
Brilliant! Thank you for your efficiency (:
